########################################################
##               MASTER and BETA BUILD                ##
########################################################
- 
  branches:
    only:
      - master
      - beta
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    virksomhetssertifikat_secret:
      secure: jEfmJzd5VxZbezh8qfl0FKpfG5A1g3jXUYEZ0dEc2CA=
    virksomhetssertifikat_pass:
      secure: zm1La2fMObjEN9S2bcX6r7JNuKjV4vVxErRARdSgDH4=    
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt bring.p12.enc -secret %virksomhetssertifikat_secret%
  before_build:
  - ps: >-
      .\appveyor-deploy\InstallVirksomhetssertifikat.ps1 -virksomhetssertifikat bring.p12;
      .\appveyor-deploy\NugetRestore.ps1;
      .\appveyor-deploy\AssemblyInfoVersionPatcher.ps1 -assemblyInfoPath  ".\SolutionItems\SharedAssemblyInfo.cs"; 
      .\appveyor-deploy\BuildPreamble.ps1   
  build:
    verbosity: minimal
  after_build:
  - ps: >-
      .\appveyor-deploy\NuspecVersionPatcher.ps1 -assembly "Digipost.Signature.Api.Client.Core\bin\Release\Digipost.Signature.Api.Client.Core.dll" -nuspec "signature-api-client.nuspec";
      nuget pack;
  artifacts:
    - path: '*.nupkg'
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1
  before_deploy:
  - ps: >-
      .\appveyor-deploy\DeployPreamble.ps1
  deploy:
    provider: NuGet
    api_key:
      secure: +8+b2Za0o/0TBgODNtnUXefTf/hhi79B0zGK7jfKQMOi8Uqs6QF0ojJyZHOkn25i
    skip_symbols: true
    artifact: /.*\.nupkg/


########################################################
##                    OTHER BRANCHES                  ##
########################################################

-
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    virksomhetssertifikat_secret:
      secure: jEfmJzd5VxZbezh8qfl0FKpfG5A1g3jXUYEZ0dEc2CA=
    virksomhetssertifikat_pass:
      secure: zm1La2fMObjEN9S2bcX6r7JNuKjV4vVxErRARdSgDH4=
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt bring.p12.enc -secret %virksomhetssertifikat_secret%
  before_build:
  - ps: >-
      .\appveyor-deploy\InstallVirksomhetssertifikat.ps1 -virksomhetssertifikat bring.p12;
      .\appveyor-deploy\NugetRestore.ps1;
      .\appveyor-deploy\BuildPreamble.ps1          
  build:
    verbosity: minimal  
  before_test:
  - ps: >-
      .\appveyor-deploy\TestPreamble.ps1
