//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class error {
    
    private string errorcodeField;
    
    private string errormessageField;
    
    private string errortypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error-code")]
    public string errorcode {
        get {
            return this.errorcodeField;
        }
        set {
            this.errorcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error-message")]
    public string errormessage {
        get {
            return this.errormessageField;
        }
        set {
            this.errormessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error-type")]
    public string errortype {
        get {
            return this.errortypeField;
        }
        set {
            this.errortypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="signature-status", Namespace="http://signering.posten.no/schema/v1")]
public partial class signaturestatus {
    
    private System.DateTime sinceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime since {
        get {
            return this.sinceField;
        }
        set {
            this.sinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class signature {
    
    private signaturestatus statusField;
    
    private object itemField;
    
    private string xadesurlField;
    
    /// <remarks/>
    public signaturestatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(notifications))]
    [System.Xml.Serialization.XmlElementAttribute("personal-identification-number", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("xades-url")]
    public string xadesurl {
        get {
            return this.xadesurlField;
        }
        set {
            this.xadesurlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class notifications {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("email", typeof(email))]
    [System.Xml.Serialization.XmlElementAttribute("sms", typeof(sms))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class email {
    
    private string addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class sms {
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class signatures {
    
    private signature[] signatureField;
    
    private string padesurlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature")]
    public signature[] signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pades-url")]
    public string padesurl {
        get {
            return this.padesurlField;
        }
        set {
            this.padesurlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class availability {
    
    private System.DateTime activationtimeField;
    
    private bool activationtimeFieldSpecified;
    
    private long availablesecondsField;
    
    private bool availablesecondsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("activation-time")]
    public System.DateTime activationtime {
        get {
            return this.activationtimeField;
        }
        set {
            this.activationtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool activationtimeSpecified {
        get {
            return this.activationtimeFieldSpecified;
        }
        set {
            this.activationtimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("available-seconds")]
    public long availableseconds {
        get {
            return this.availablesecondsField;
        }
        set {
            this.availablesecondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool availablesecondsSpecified {
        get {
            return this.availablesecondsFieldSpecified;
        }
        set {
            this.availablesecondsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="portal-document", Namespace="http://signering.posten.no/schema/v1")]
public partial class portaldocument {
    
    private string titleField;
    
    private string nonsensitivetitleField;
    
    private string descriptionField;
    
    private string hrefField;
    
    private string mimeField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nonsensitive-title")]
    public string nonsensitivetitle {
        get {
            return this.nonsensitivetitleField;
        }
        set {
            this.nonsensitivetitleField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mime {
        get {
            return this.mimeField;
        }
        set {
            this.mimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="notifications-using-lookup", Namespace="http://signering.posten.no/schema/v1")]
public partial class notificationsusinglookup {
    
    private enabled emailField;
    
    private enabled smsField;
    
    /// <remarks/>
    public enabled email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public enabled sms {
        get {
            return this.smsField;
        }
        set {
            this.smsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class enabled {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="portal-signer", Namespace="http://signering.posten.no/schema/v1")]
public partial class portalsigner {
    
    private object itemField;
    
    private signaturetype signaturetypeField;
    
    private bool signaturetypeFieldSpecified;
    
    private object item1Field;
    
    private signingonbehalfof onbehalfofField;
    
    private bool onbehalfofFieldSpecified;
    
    private int orderField;
    
    private bool orderFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identified-by-contact-information", typeof(enabled))]
    [System.Xml.Serialization.XmlElementAttribute("personal-identification-number", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-type")]
    public signaturetype signaturetype {
        get {
            return this.signaturetypeField;
        }
        set {
            this.signaturetypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool signaturetypeSpecified {
        get {
            return this.signaturetypeFieldSpecified;
        }
        set {
            this.signaturetypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("notifications", typeof(notifications))]
    [System.Xml.Serialization.XmlElementAttribute("notifications-using-lookup", typeof(notificationsusinglookup))]
    public object Item1 {
        get {
            return this.item1Field;
        }
        set {
            this.item1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-behalf-of")]
    public signingonbehalfof onbehalfof {
        get {
            return this.onbehalfofField;
        }
        set {
            this.onbehalfofField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onbehalfofSpecified {
        get {
            return this.onbehalfofFieldSpecified;
        }
        set {
            this.onbehalfofFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderSpecified {
        get {
            return this.orderFieldSpecified;
        }
        set {
            this.orderFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="signature-type", Namespace="http://signering.posten.no/schema/v1")]
public enum signaturetype {
    
    /// <remarks/>
    ADVANCED_ELECTRONIC_SIGNATURE,
    
    /// <remarks/>
    AUTHENTICATED_ELECTRONIC_SIGNATURE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="signing-on-behalf-of", Namespace="http://signering.posten.no/schema/v1")]
public enum signingonbehalfof {
    
    /// <remarks/>
    SELF,
    
    /// <remarks/>
    OTHER,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="signer-status", Namespace="http://signering.posten.no/schema/v1")]
public partial class signerstatus {
    
    private string signerField;
    
    private System.DateTime sinceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string signer {
        get {
            return this.signerField;
        }
        set {
            this.signerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime since {
        get {
            return this.sinceField;
        }
        set {
            this.sinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="signer-specific-url", Namespace="http://signering.posten.no/schema/v1")]
public partial class signerspecificurl {
    
    private string signerField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string signer {
        get {
            return this.signerField;
        }
        set {
            this.signerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="direct-document", Namespace="http://signering.posten.no/schema/v1")]
public partial class directdocument {
    
    private string titleField;
    
    private string descriptionField;
    
    private string hrefField;
    
    private string mimeField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mime {
        get {
            return this.mimeField;
        }
        set {
            this.mimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1")]
public partial class sender {
    
    private string organizationnumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organization-number")]
    public string organizationnumber {
        get {
            return this.organizationnumberField;
        }
        set {
            this.organizationnumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="direct-signer", Namespace="http://signering.posten.no/schema/v1")]
public partial class directsigner {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private signaturetype signaturetypeField;
    
    private bool signaturetypeFieldSpecified;
    
    private signingonbehalfof onbehalfofField;
    
    private bool onbehalfofFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("personal-identification-number", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("signer-identifier", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-type")]
    public signaturetype signaturetype {
        get {
            return this.signaturetypeField;
        }
        set {
            this.signaturetypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool signaturetypeSpecified {
        get {
            return this.signaturetypeFieldSpecified;
        }
        set {
            this.signaturetypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("on-behalf-of")]
    public signingonbehalfof onbehalfof {
        get {
            return this.onbehalfofField;
        }
        set {
            this.onbehalfofField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onbehalfofSpecified {
        get {
            return this.onbehalfofFieldSpecified;
        }
        set {
            this.onbehalfofFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://signering.posten.no/schema/v1", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("personal-identification-number")]
    personalidentificationnumber,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("signer-identifier")]
    signeridentifier,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="exit-urls", Namespace="http://signering.posten.no/schema/v1")]
public partial class exiturls {
    
    private string completionurlField;
    
    private string rejectionurlField;
    
    private string errorurlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("completion-url")]
    public string completionurl {
        get {
            return this.completionurlField;
        }
        set {
            this.completionurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rejection-url")]
    public string rejectionurl {
        get {
            return this.rejectionurlField;
        }
        set {
            this.rejectionurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("error-url")]
    public string errorurl {
        get {
            return this.errorurlField;
        }
        set {
            this.errorurlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("direct-signature-job-request", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class directsignaturejobrequest {
    
    private string referenceField;
    
    private exiturls exiturlsField;
    
    private statusretrievalmethod statusretrievalmethodField;
    
    private bool statusretrievalmethodFieldSpecified;
    
    /// <remarks/>
    public string reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exit-urls")]
    public exiturls exiturls {
        get {
            return this.exiturlsField;
        }
        set {
            this.exiturlsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status-retrieval-method")]
    public statusretrievalmethod statusretrievalmethod {
        get {
            return this.statusretrievalmethodField;
        }
        set {
            this.statusretrievalmethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusretrievalmethodSpecified {
        get {
            return this.statusretrievalmethodFieldSpecified;
        }
        set {
            this.statusretrievalmethodFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="status-retrieval-method", Namespace="http://signering.posten.no/schema/v1")]
public enum statusretrievalmethod {
    
    /// <remarks/>
    WAIT_FOR_CALLBACK,
    
    /// <remarks/>
    POLLING,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("direct-signature-job-manifest", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class directsignaturejobmanifest {
    
    private directsigner[] signerField;
    
    private sender senderField;
    
    private directdocument documentField;
    
    private authenticationlevel requiredauthenticationField;
    
    private bool requiredauthenticationFieldSpecified;
    
    private identifierinsigneddocuments identifierinsigneddocumentsField;
    
    private bool identifierinsigneddocumentsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signer")]
    public directsigner[] signer {
        get {
            return this.signerField;
        }
        set {
            this.signerField = value;
        }
    }
    
    /// <remarks/>
    public sender sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public directdocument document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("required-authentication")]
    public authenticationlevel requiredauthentication {
        get {
            return this.requiredauthenticationField;
        }
        set {
            this.requiredauthenticationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool requiredauthenticationSpecified {
        get {
            return this.requiredauthenticationFieldSpecified;
        }
        set {
            this.requiredauthenticationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identifier-in-signed-documents")]
    public identifierinsigneddocuments identifierinsigneddocuments {
        get {
            return this.identifierinsigneddocumentsField;
        }
        set {
            this.identifierinsigneddocumentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identifierinsigneddocumentsSpecified {
        get {
            return this.identifierinsigneddocumentsFieldSpecified;
        }
        set {
            this.identifierinsigneddocumentsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="authentication-level", Namespace="http://signering.posten.no/schema/v1")]
public enum authenticationlevel {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="identifier-in-signed-documents", Namespace="http://signering.posten.no/schema/v1")]
public enum identifierinsigneddocuments {
    
    /// <remarks/>
    PERSONAL_IDENTIFICATION_NUMBER_AND_NAME,
    
    /// <remarks/>
    DATE_OF_BIRTH_AND_NAME,
    
    /// <remarks/>
    NAME,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("direct-signature-job-response", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class directsignaturejobresponse {
    
    private long signaturejobidField;
    
    private signerspecificurl[] redirecturlField;
    
    private string statusurlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-job-id")]
    public long signaturejobid {
        get {
            return this.signaturejobidField;
        }
        set {
            this.signaturejobidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("redirect-url")]
    public signerspecificurl[] redirecturl {
        get {
            return this.redirecturlField;
        }
        set {
            this.redirecturlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status-url")]
    public string statusurl {
        get {
            return this.statusurlField;
        }
        set {
            this.statusurlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("direct-signature-job-status-response", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class directsignaturejobstatusresponse {
    
    private long signaturejobidField;
    
    private directsignaturejobstatus signaturejobstatusField;
    
    private signerstatus[] statusField;
    
    private string confirmationurlField;
    
    private signerspecificurl[] xadesurlField;
    
    private string padesurlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-job-id")]
    public long signaturejobid {
        get {
            return this.signaturejobidField;
        }
        set {
            this.signaturejobidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-job-status")]
    public directsignaturejobstatus signaturejobstatus {
        get {
            return this.signaturejobstatusField;
        }
        set {
            this.signaturejobstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status")]
    public signerstatus[] status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("confirmation-url")]
    public string confirmationurl {
        get {
            return this.confirmationurlField;
        }
        set {
            this.confirmationurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("xades-url")]
    public signerspecificurl[] xadesurl {
        get {
            return this.xadesurlField;
        }
        set {
            this.xadesurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pades-url")]
    public string padesurl {
        get {
            return this.padesurlField;
        }
        set {
            this.padesurlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="direct-signature-job-status", Namespace="http://signering.posten.no/schema/v1")]
public enum directsignaturejobstatus {
    
    /// <remarks/>
    IN_PROGRESS,
    
    /// <remarks/>
    COMPLETED_SUCCESSFULLY,
    
    /// <remarks/>
    FAILED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("portal-signature-job-request", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class portalsignaturejobrequest {
    
    private string referenceField;
    
    /// <remarks/>
    public string reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("portal-signature-job-manifest", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class portalsignaturejobmanifest {
    
    private portalsigner[] signersField;
    
    private sender senderField;
    
    private portaldocument documentField;
    
    private authenticationlevel requiredauthenticationField;
    
    private bool requiredauthenticationFieldSpecified;
    
    private availability availabilityField;
    
    private identifierinsigneddocuments identifierinsigneddocumentsField;
    
    private bool identifierinsigneddocumentsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("signer", IsNullable=false)]
    public portalsigner[] signers {
        get {
            return this.signersField;
        }
        set {
            this.signersField = value;
        }
    }
    
    /// <remarks/>
    public sender sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public portaldocument document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("required-authentication")]
    public authenticationlevel requiredauthentication {
        get {
            return this.requiredauthenticationField;
        }
        set {
            this.requiredauthenticationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool requiredauthenticationSpecified {
        get {
            return this.requiredauthenticationFieldSpecified;
        }
        set {
            this.requiredauthenticationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public availability availability {
        get {
            return this.availabilityField;
        }
        set {
            this.availabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("identifier-in-signed-documents")]
    public identifierinsigneddocuments identifierinsigneddocuments {
        get {
            return this.identifierinsigneddocumentsField;
        }
        set {
            this.identifierinsigneddocumentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identifierinsigneddocumentsSpecified {
        get {
            return this.identifierinsigneddocumentsFieldSpecified;
        }
        set {
            this.identifierinsigneddocumentsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("portal-signature-job-response", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class portalsignaturejobresponse {
    
    private long signaturejobidField;
    
    private string cancellationurlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-job-id")]
    public long signaturejobid {
        get {
            return this.signaturejobidField;
        }
        set {
            this.signaturejobidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cancellation-url")]
    public string cancellationurl {
        get {
            return this.cancellationurlField;
        }
        set {
            this.cancellationurlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://signering.posten.no/schema/v1")]
[System.Xml.Serialization.XmlRootAttribute("portal-signature-job-status-change-response", Namespace="http://signering.posten.no/schema/v1", IsNullable=false)]
public partial class portalsignaturejobstatuschangeresponse {
    
    private long signaturejobidField;
    
    private portalsignaturejobstatus statusField;
    
    private string confirmationurlField;
    
    private string cancellationurlField;
    
    private signatures signaturesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signature-job-id")]
    public long signaturejobid {
        get {
            return this.signaturejobidField;
        }
        set {
            this.signaturejobidField = value;
        }
    }
    
    /// <remarks/>
    public portalsignaturejobstatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("confirmation-url")]
    public string confirmationurl {
        get {
            return this.confirmationurlField;
        }
        set {
            this.confirmationurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cancellation-url")]
    public string cancellationurl {
        get {
            return this.cancellationurlField;
        }
        set {
            this.cancellationurlField = value;
        }
    }
    
    /// <remarks/>
    public signatures signatures {
        get {
            return this.signaturesField;
        }
        set {
            this.signaturesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="portal-signature-job-status", Namespace="http://signering.posten.no/schema/v1")]
public enum portalsignaturejobstatus {
    
    /// <remarks/>
    IN_PROGRESS,
    
    /// <remarks/>
    COMPLETED_SUCCESSFULLY,
    
    /// <remarks/>
    FAILED,
}
