name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore 
      - name: Decode certificate
        run: echo ${{ secrets.BRING_CERTIFICATE_PASSWORD_ENCRYPTION_KEY }} | base64 --decode > $(echo ${GITHUB_WORKSPACE})/Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12
      - name: Set certificate path
        run: dotnet user-secrets set Certificate:Path:Absolute $(echo ${GITHUB_WORKSPACE})/Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12 --project Digipost.Signature.Api.Client.Core
      - name: Set certificate password
        run: dotnet user-secrets set Certificate:Password ${{ secrets.BRING_CERTIFICATE_PASSWORD }} --project Digipost.Signature.Api.Client.Core >/dev/null 2>&1
      - name: Test
        run: dotnet test --no-restore --verbosity normal
