name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.403
      - name: Install dependencies
        run: dotnet restore 
      - name: Decode certificate
        run: echo -n $(echo ${{ secrets.ENCODED_SMOKE_TEST_CERTIFICATE }}) | base64 -d > $(echo ${GITHUB_WORKSPACE})/Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12
      - name: checksum p12 (for debug-purposes)
        run: sha256sum $(echo ${GITHUB_WORKSPACE})/Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12
      - name: Set certificate path
        run: dotnet user-secrets set Certificate:Path:Absolute $(echo ${GITHUB_WORKSPACE})/Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12 --project Digipost.Signature.Api.Client.Core
      - name: Set certificate password
        run: dotnet user-secrets set Certificate:Password ${{ secrets.SMOKE_TEST_CERTIFICATE_PASSWORD }} --project Digipost.Signature.Api.Client.Core >/dev/null 2>&1
      - name: Test
        run: dotnet test --no-restore --verbosity normal
